### PR TITLE
Correct a sentence to match french language

### PR DESCRIPTION
**Pull request by ASponch**
A small correction in translation.

### CODE REVIEW

**Comment by ASponch** [comment]
Hello, I'm sorry, I use VSCode instead of notepad++ because I'm a linux user. Anyway, the modification that I made is on line 142.

**Comment by olegkrivtsov** [comment]
Hey @ASponch, sorry, but this pull request has merging conflicts, too. Could you please check and fix if possible?

**Comment by ASponch** [comment]
Hello, I resolved the conflicts :)

**Comment by olegkrivtsov** [comment]
Hmm.. something is wrong with line endings in *Files changed*... @ASponch, sorry, but can you please fix that?

**Comment by ASponch** [comment]
Done ! déclareons => déclarons :)

**Comment by olegkrivtsov** [comment]
Thanks @ASponch!

**Pull request merged**
