### PR TITLE
Chapter 12 is translated

### PR DESCRIPTION
**Pull request by glengemann**

### CODE REVIEW

**Comment by olegkrivtsov** [comment]
Merged, thanks!

**Comment by olegkrivtsov** [comment]
Hi! BTW, I've just published your Spanish translation: https://olegkrivtsov.github.io/using-zend-framework-3-book/html/es/toc.html 

Thanks a lot and keep up the great work!

**Comment by glengemann** [comment]
Thanks, you have done a good book. Congratulations on your Zend Certified!

**Comment by olegkrivtsov** [comment]
Hi @omerta Thanks! Would you like to be a moderator of comments coming from Spanish readers? I can add your email to Disqus, so you will receive notifications on new comments. Please tell me your email.

**Comment by glengemann** [comment]
@olegkrivtsov! Yes I can, It will be a challenge for me. My email is omerta@unefa-glug.org.ve.

**Comment by olegkrivtsov** [comment]
Hi @omerta Thanks! Could you please register on Disqus https://disqus.com/ with your email address so I add you as a moderator?

**Comment by glengemann** [comment]
Privyet @olegkrivtsov. Ready! In other hand, I have noticed that perhaps is not uniform the use of  `**` and ` `` `. For example, `*bootstrap-theme.min.css*` but `` `jquery-2.2.4.min.js` ``. This is important?

**Comment by olegkrivtsov** [comment]
Hi @omerta When I'm trying to add your email omerta@unefa-glug.org.ve as a moderator to Disqus, I see the following message: "No user found with this username." Are you sure you registered at Disqus?

**Comment by glengemann** [comment]
You try to find me between your followers. Or easier [this is the link](https://disqus.com/by/glgomerta/) to my profile on Disqus! See you @olegkrivtsov

**Comment by olegkrivtsov** [comment]
@omerta I finally managed to add you. Please moderate only Spanish comments, leaving all others intact.

**Pull request merged**
