### PR TITLE
Chapter 15, some fix words in the English text and translate into Spa…

### PR DESCRIPTION
**Pull request by glengemann**
Chapter 15, some fix words in the English text and translate into Spanish.

### CODE REVIEW

**Comment by olegkrivtsov** [comment]
Hi @omerta. Thanks for your translation! But, to merge your pull request I need the following:

1. That you translate all chapters into Spanish.
2. That you support your translation for long-term (fix mistakes, etc). I don't know Spanish, so it would be very difficult for me.

I understand that translating such a large book into Spanish is a very large work, so I understand if you do not plan to do it. Just let me know.

BTW, when we translated this book into Russian, we spent more than month of a full-time work.

**Comment by glengemann** [comment]
Yes, I want to translate all book it will be good for my too. Spanish is my first language, English the second and PHP the third :).

I can fix and update the translation. I have not read all the book but I think that it can be translated this year.

**Comment by olegkrivtsov** [comment]
Great!

**Comment by olegkrivtsov** [comment]
Merged, thanks!

**Pull request merged**
