### PR TITLE
Gbell fixes2

### PR DESCRIPTION
**Pull request by bitwombat**
Sorry, Oleg, my editor stripped off trailing spaces all throughout the file, cluttering the diff view.  I don't see any way to ignore whitespace here in github.  Once your eye keys into the slightly darker highlights at the ends of lines, you'll be able to skim past them.

### CODE REVIEW

**Comment by olegkrivtsov** [comment]
I've incorporated your changes manually, thanks. I appreciate your grammar fixes. In the future, please use Notepad++ editor to avoid problems with encoding, whitespaces, etc. Please also ensure you use 4 spaces instead of tabs in Notepad++. Thanks!

**Comment by bitwombat** [comment]
I use Vim set to UTF-8 and 4-spaces as tabs... equal to your source.  But I have a plugin that strips useless EOL whitespace, which I didn't notice was causing diffs until it was too late.  Will possibly crop up with other contributors if you don't remove them from the source.

**Comment by bitwombat** [comment]
Looks like you missed a bunch.  Can you merge with the EOL whitespace removal, or should I re-do the edits?

**Comment by olegkrivtsov** [comment]
No need to re-do. I've added most of your fixes and missed some that I didn't like.

**Comment by bitwombat** [comment]
Well at least one was correcting grammar :)  I don't want to waste my time creating changes that don't get accepted, but I don't want you accepting things you don't like.  But grammar fixes are objective.

Like this one:

-In this chapter, we've covered the usage of the Object Relational Mapper (ORM) component of 
-Doctrine library. The ORM is designed for database management in object-oriented style. With ORM,
-you map a database table to a PHP class called entity, and columns of that table are mapped to the 
-properties of the class. 

"**the** Doctrine library" or just "Doctrine".
"**an** object-oriented style"
"called entity" isn't right, and my PR had my best re-work of this that I could think of.

-but we cover its usage in this book, because 

No commas before 'because'.

Maybe you're only interested in grammar and punctuation fixes, and I shouldn't try to clarify anything.  Perhaps we have a different explanatory style and that sort of input from me isn't useful to you.

Let me know, I'd love to help with the resource.

**Comment by olegkrivtsov** [comment]
Hi @bitwombat 

> Well at least one was correcting grammar :) I don't want to waste my time creating changes that don't get accepted, but I don't want you accepting things you don't like. But grammar fixes are objective.

Since I'm the main author and the maintainer of this book, I think it is normal that I approve or reject changes. You will face with this if you contribute to any other project, like Zend Framework, or Linux kernel. Sorry if that disappointed you.

> Like this one:

I appreciate changes that fix incorrect grammar (sorry, I actually missed those listed above, will fix those). At the same time, I'm not a fan of just "reformulating" sentences, because this is subject to personal writing style, etc. So, if you'd like to suggest some change, please discuss it with me first. 

> Let me know, I'd love to help with the resource.

I really appreciate constructive critics. If you have some suggestions/fixes - please submit them. But, I'd like to have a chance to review and moderate them.

**Comment by bitwombat** [comment]
Yes, yes, of course, it's your book.  What I'm saying is that I need to understand what changes you find acceptable so I'm not wasting time.

But grammar changes aren't opinion, so I didn't understand why some of those were rejected.

For example, with lists, each item should be a continuation of the leading sentence.

So I need do three things:

1) Buy bread
2) Write code
3) Get rest

With your lists, you violate this, which makes the reading bumpy.  For example with this lead-in:

> For demonstration of Doctrine ORM usage, in this chapter, we will create a real-life *Blog*
> website that _does_ the following:

Not all items fit.  Here they are.

>  * Stores blog posts in a database and provides a user interface for accessing and managing those posts. 

Fits.  That's something it does.

>  * It is assumed that the blog has the single author of its posts, while comments can be added
>    by multiple blog readers.

Doesn't fit.  That's a statement of an assumption.

>  * The website has two pages: *Home* page and *Admin* page. The first one displays the list
> of recently added posts, while the latter one allows to add, edit, view and delete posts.

Doesn't fit.  That's a description of pages within it.

Maybe this is the sentence re-working that you're not interested in, I'm not sure.  No worries, just let me know so I can target my corrections.

~gb

**Comment by olegkrivtsov** [comment]
> Yes, yes, of course, it's your book. What I'm saying is that I need to understand what changes you find acceptable so I'm not wasting time.

You can propose any change you wish, but it may be subject to discussion. I typically accept all bug fixes, typo reports, grammar fixes, mistake fixes without any discussion.

>But grammar changes aren't opinion, so I didn't understand why some of those were rejected.

If you clearly see that I missed some grammar fix, please report. My English is not perfect, so I could just miss something. Your last PR was not very convenient to analyze in Git Diff, so I could miss something.

> With your lists, you violate this, which makes the reading bumpy. For example with this lead-in:

Hmm.. my personal opinion here is that this is not a grammar mistake. I easily understand such list styling and see no major problems with it. Please let's leave this list as it is.

**Comment by bitwombat** [comment]
http://www.quickanddirtytips.com/education/grammar/how-to-format-a-bulleted-list-and-more?page=2

**Comment by olegkrivtsov** [comment]
Thanks for the link. OK, I will modify this list as you suggest. Still, I think this is not a mistake and fixing it is not a drammatical improvement.

**Pull request closed without merging**
