### PR TITLE
Contribution with the ZF3 book, service-manager chapter

### PR DESCRIPTION
**Pull request by DarwinC**
Hi, this is my contribution for this proyect. I hope it will usefull.
Spanish translation.

### CODE REVIEW

**Comment by olegkrivtsov** [comment]
Merged, thanks!

**Comment by Morteza86** [comment]
hello
thank you so much.
this book is very useful.
if you can, please provide unit test chapter too.
good luck.

**Comment by DarwinC** [comment]
Hi,
when i have some time, i'll try to do it.
Regards.

2017-08-14 12:51 GMT-03:00 Morteza86 <notifications@github.com>:

**Comment by glengemann** [comment]
This is not a chapter is a subsection of chapter 3. The chapter 3 was translated and merge in the issue [28](https://github.com/olegkrivtsov/using-zend-framework-3-book/pull/28).

**Pull request merged**
