### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by ASponch**
In french, we said "Programmation orientée objet" (= POO) instead of "Oriented programmation objet" (= OOP)

### CODE REVIEW

**Comment by ASponch** [comment]
For the same reason as the previous PR, the modification is on line 28.

**Comment by olegkrivtsov** [comment]
Hey @ASponch, could you please check for merging conflicts in your pull request? I'm not sure how to resolve them myself. Please feel free to ask if you have any questions. :)

**Comment by ASponch** [comment]
That's done :)

**Comment by olegkrivtsov** [comment]
Hey @ASponch, I see from the *Files changed*, that you use tabs instead of 4 spaces, can you please fix that? If you have any questions, please ask.

**Comment by ASponch** [comment]
Hello @olegkrivtsov, I think that was good now.

**Comment by olegkrivtsov** [comment]
Hey @ASponch, sorry, but I still see unresolved conflicts. Can you please re-check?

**Comment by olegkrivtsov** [comment]
Closing since it has unresolved conflicts.

**Comment by ASponch** [comment]
Sorry, I'm late. I work on an other project and put stand by my ZF3 reading. Maybe in the future :)

**Pull request closed without merging**
